services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=vinsguru
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=productdb
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@vinsguru.com
      - PGADMIN_DEFAULT_PASSWORD=admin
#      - PGADMIN_CONFIG_SERVER_MODE='False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
